/* soapClient.cpp
   Generated by gSOAP 2.8.51 for service1.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.51 2017-08-15 05:58:47 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__deleteFiles *ns1__deleteFiles_, ns1__deleteFilesResponse &ns1__deleteFilesResponse_)
{	struct __ns1__deleteFiles soap_tmp___ns1__deleteFiles;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__deleteFiles.ns1__deleteFiles_ = ns1__deleteFiles_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteFiles(soap, &soap_tmp___ns1__deleteFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteFiles(soap, &soap_tmp___ns1__deleteFiles, "-ns1:deleteFiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteFiles(soap, &soap_tmp___ns1__deleteFiles, "-ns1:deleteFiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__deleteFilesResponse*>(&ns1__deleteFilesResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__deleteFilesResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteFilesResponse_.soap_get(soap, "ns1:deleteFilesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createBucket(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__createBucket *ns1__createBucket_, ns1__createBucketResponse &ns1__createBucketResponse_)
{	struct __ns1__createBucket soap_tmp___ns1__createBucket;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__createBucket.ns1__createBucket_ = ns1__createBucket_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__createBucket(soap, &soap_tmp___ns1__createBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__createBucket(soap, &soap_tmp___ns1__createBucket, "-ns1:createBucket", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__createBucket(soap, &soap_tmp___ns1__createBucket, "-ns1:createBucket", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__createBucketResponse*>(&ns1__createBucketResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__createBucketResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__createBucketResponse_.soap_get(soap, "ns1:createBucketResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteBucket(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__deleteBucket *ns1__deleteBucket_, ns1__deleteBucketResponse &ns1__deleteBucketResponse_)
{	struct __ns1__deleteBucket soap_tmp___ns1__deleteBucket;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__deleteBucket.ns1__deleteBucket_ = ns1__deleteBucket_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteBucket(soap, &soap_tmp___ns1__deleteBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteBucket(soap, &soap_tmp___ns1__deleteBucket, "-ns1:deleteBucket", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteBucket(soap, &soap_tmp___ns1__deleteBucket, "-ns1:deleteBucket", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__deleteBucketResponse*>(&ns1__deleteBucketResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__deleteBucketResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteBucketResponse_.soap_get(soap, "ns1:deleteBucketResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__doesBucketExists(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__doesBucketExists *ns1__doesBucketExists_, ns1__doesBucketExistsResponse &ns1__doesBucketExistsResponse_)
{	struct __ns1__doesBucketExists soap_tmp___ns1__doesBucketExists;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__doesBucketExists.ns1__doesBucketExists_ = ns1__doesBucketExists_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__doesBucketExists(soap, &soap_tmp___ns1__doesBucketExists);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__doesBucketExists(soap, &soap_tmp___ns1__doesBucketExists, "-ns1:doesBucketExists", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__doesBucketExists(soap, &soap_tmp___ns1__doesBucketExists, "-ns1:doesBucketExists", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__doesBucketExistsResponse*>(&ns1__doesBucketExistsResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__doesBucketExistsResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__doesBucketExistsResponse_.soap_get(soap, "ns1:doesBucketExistsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getBucketNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__getBucketNames *ns1__getBucketNames_, ns1__getBucketNamesResponse &ns1__getBucketNamesResponse_)
{	struct __ns1__getBucketNames soap_tmp___ns1__getBucketNames;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__getBucketNames.ns1__getBucketNames_ = ns1__getBucketNames_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getBucketNames(soap, &soap_tmp___ns1__getBucketNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getBucketNames(soap, &soap_tmp___ns1__getBucketNames, "-ns1:getBucketNames", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getBucketNames(soap, &soap_tmp___ns1__getBucketNames, "-ns1:getBucketNames", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__getBucketNamesResponse*>(&ns1__getBucketNamesResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__getBucketNamesResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getBucketNamesResponse_.soap_get(soap, "ns1:getBucketNamesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getBucketFileNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__getBucketFileNames *ns1__getBucketFileNames_, ns1__getBucketFileNamesResponse &ns1__getBucketFileNamesResponse_)
{	struct __ns1__getBucketFileNames soap_tmp___ns1__getBucketFileNames;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__getBucketFileNames.ns1__getBucketFileNames_ = ns1__getBucketFileNames_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getBucketFileNames(soap, &soap_tmp___ns1__getBucketFileNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getBucketFileNames(soap, &soap_tmp___ns1__getBucketFileNames, "-ns1:getBucketFileNames", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getBucketFileNames(soap, &soap_tmp___ns1__getBucketFileNames, "-ns1:getBucketFileNames", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__getBucketFileNamesResponse*>(&ns1__getBucketFileNamesResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__getBucketFileNamesResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getBucketFileNamesResponse_.soap_get(soap, "ns1:getBucketFileNamesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__doesFileExists(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__doesFileExists *ns1__doesFileExists_, ns1__doesFileExistsResponse &ns1__doesFileExistsResponse_)
{	struct __ns1__doesFileExists soap_tmp___ns1__doesFileExists;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__doesFileExists.ns1__doesFileExists_ = ns1__doesFileExists_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__doesFileExists(soap, &soap_tmp___ns1__doesFileExists);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__doesFileExists(soap, &soap_tmp___ns1__doesFileExists, "-ns1:doesFileExists", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__doesFileExists(soap, &soap_tmp___ns1__doesFileExists, "-ns1:doesFileExists", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__doesFileExistsResponse*>(&ns1__doesFileExistsResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__doesFileExistsResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__doesFileExistsResponse_.soap_get(soap, "ns1:doesFileExistsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getFileMessage(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__getFileMessage *ns1__getFileMessage_, ns1__getFileMessageResponse &ns1__getFileMessageResponse_)
{	struct __ns1__getFileMessage soap_tmp___ns1__getFileMessage;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__getFileMessage.ns1__getFileMessage_ = ns1__getFileMessage_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getFileMessage(soap, &soap_tmp___ns1__getFileMessage);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getFileMessage(soap, &soap_tmp___ns1__getFileMessage, "-ns1:getFileMessage", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getFileMessage(soap, &soap_tmp___ns1__getFileMessage, "-ns1:getFileMessage", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__getFileMessageResponse*>(&ns1__getFileMessageResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__getFileMessageResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getFileMessageResponse_.soap_get(soap, "ns1:getFileMessageResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getFileDetail(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__getFileDetail *ns1__getFileDetail_, ns1__getFileDetailResponse &ns1__getFileDetailResponse_)
{	struct __ns1__getFileDetail soap_tmp___ns1__getFileDetail;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__getFileDetail.ns1__getFileDetail_ = ns1__getFileDetail_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getFileDetail(soap, &soap_tmp___ns1__getFileDetail);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getFileDetail(soap, &soap_tmp___ns1__getFileDetail, "-ns1:getFileDetail", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getFileDetail(soap, &soap_tmp___ns1__getFileDetail, "-ns1:getFileDetail", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__getFileDetailResponse*>(&ns1__getFileDetailResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__getFileDetailResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getFileDetailResponse_.soap_get(soap, "ns1:getFileDetailResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteOneFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__deleteOneFile *ns1__deleteOneFile_, ns1__deleteOneFileResponse &ns1__deleteOneFileResponse_)
{	struct __ns1__deleteOneFile soap_tmp___ns1__deleteOneFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__deleteOneFile.ns1__deleteOneFile_ = ns1__deleteOneFile_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteOneFile(soap, &soap_tmp___ns1__deleteOneFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteOneFile(soap, &soap_tmp___ns1__deleteOneFile, "-ns1:deleteOneFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteOneFile(soap, &soap_tmp___ns1__deleteOneFile, "-ns1:deleteOneFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__deleteOneFileResponse*>(&ns1__deleteOneFileResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__deleteOneFileResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteOneFileResponse_.soap_get(soap, "ns1:deleteOneFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteBatchFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__deleteBatchFile *ns1__deleteBatchFile_, ns1__deleteBatchFileResponse &ns1__deleteBatchFileResponse_)
{	struct __ns1__deleteBatchFile soap_tmp___ns1__deleteBatchFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__deleteBatchFile.ns1__deleteBatchFile_ = ns1__deleteBatchFile_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteBatchFile(soap, &soap_tmp___ns1__deleteBatchFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteBatchFile(soap, &soap_tmp___ns1__deleteBatchFile, "-ns1:deleteBatchFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteBatchFile(soap, &soap_tmp___ns1__deleteBatchFile, "-ns1:deleteBatchFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__deleteBatchFileResponse*>(&ns1__deleteBatchFileResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__deleteBatchFileResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteBatchFileResponse_.soap_get(soap, "ns1:deleteBatchFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteFileByName(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__deleteFileByName *ns1__deleteFileByName_, ns1__deleteFileByNameResponse &ns1__deleteFileByNameResponse_)
{	struct __ns1__deleteFileByName soap_tmp___ns1__deleteFileByName;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__deleteFileByName.ns1__deleteFileByName_ = ns1__deleteFileByName_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteFileByName(soap, &soap_tmp___ns1__deleteFileByName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteFileByName(soap, &soap_tmp___ns1__deleteFileByName, "-ns1:deleteFileByName", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteFileByName(soap, &soap_tmp___ns1__deleteFileByName, "-ns1:deleteFileByName", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__deleteFileByNameResponse*>(&ns1__deleteFileByNameResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__deleteFileByNameResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteFileByNameResponse_.soap_get(soap, "ns1:deleteFileByNameResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__uploadFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__uploadFile *ns1__uploadFile_, ns1__uploadFileResponse &ns1__uploadFileResponse_)
{	struct __ns1__uploadFile soap_tmp___ns1__uploadFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__uploadFile.ns1__uploadFile_ = ns1__uploadFile_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__uploadFile(soap, &soap_tmp___ns1__uploadFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__uploadFile(soap, &soap_tmp___ns1__uploadFile, "-ns1:uploadFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__uploadFile(soap, &soap_tmp___ns1__uploadFile, "-ns1:uploadFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__uploadFileResponse*>(&ns1__uploadFileResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__uploadFileResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__uploadFileResponse_.soap_get(soap, "ns1:uploadFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__downLoadFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__downLoadFile *ns1__downLoadFile_, ns1__downLoadFileResponse &ns1__downLoadFileResponse_)
{	struct __ns1__downLoadFile soap_tmp___ns1__downLoadFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websiteman.cnki.net:80/Ceph/CephStoragePort";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__downLoadFile.ns1__downLoadFile_ = ns1__downLoadFile_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__downLoadFile(soap, &soap_tmp___ns1__downLoadFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__downLoadFile(soap, &soap_tmp___ns1__downLoadFile, "-ns1:downLoadFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__downLoadFile(soap, &soap_tmp___ns1__downLoadFile, "-ns1:downLoadFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__downLoadFileResponse*>(&ns1__downLoadFileResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__downLoadFileResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__downLoadFileResponse_.soap_get(soap, "ns1:downLoadFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
